# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np ## here we are importing the Numpy library, and we are "naming/calling" it np   

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5) 
## here we create a 1D array with values starting from 1 and ending at 15, 16 is the stop value and is not included.
## then we use the mehtod reshape() - which change the shape of our array - in this case from a 1D array to a 2D array
## inside the parameter we give the amount of rows and columns we want - in this case 3 rows and 5 columns

In [5]:
print(A.ndim, A.shape, A.size, A.dtype) ## with the help of the different attributes of the NumPy array object 
## we call these attribute on the instance A and we can get the :
#dimension, shape - number of rows and columns, size - the total number of elements, dtype - the data type of the elements the array contain.

2 (3, 5) 15 int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [6]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2 ## 

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [7]:
sub = B - C  ## sub stores the result of B - C, this allows us to later use this result if needed. 
print(sub)
## or simply
print(B - C) ## here we simply just print the result without storing the result. 

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]


In [8]:
mult = B * C
print(mult)
## or simply
print(B * C)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [9]:
matrix = B @ C 
print(matrix)
## or simply
print(B @ C)

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [10]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
## Exponent
exponent = np.exp(B)
print(exponent)
## or simply
print(np.exp(B))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [12]:
## Minimum value in whole matrix
print(np.min(B)) ## function that returns the minimum value of the entire array B

1


In [13]:
## Minimum value in each row 
print(np.min(B, axis = 1)) ## function that returns the minimum value of the array for each row (row index starts with 1)
## inside the parameter you specify what axis you want to check the min value for.

[1 4 7]


In [14]:
## Minimum value in each column 
print(np.min(B, axis = 0)) ## function that returns the minmum value of the array for each column (column index starrts with 1)

[1 2 3]


In [15]:
## Find index value for the minimum value in whole matrix 
np.argmin(B) ## function that returns the minimum 

0

In [14]:
## Find index value for the minimum value in each row
np.argmin(B, axis = 1) ## function that returns the minimu value for specified axis 

array([0, 0, 0])

In [16]:
## calculate sum for ALL elements
np.sum(B) ## function that calculates the sum of all the elements in array 

45

In [17]:
## Calculate the MEAN for each column 
np.mean(B, axis = 0) ## fucntion that calculates the mean for specified axis 

array([4., 5., 6.])

In [18]:
## Calculate the MEDIAN for each column
np.median(B, axis = 0) ## fucntion that calculates the mean for specified axis

array([4., 5., 6.])

### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [19]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [20]:
A[1] 

array([ 6,  7,  8,  9, 10])

**Answer:**

In [20]:
## in the given example above we have provided with index 1 which is the second row in the array, 
## this means that we are now only accesing the elements within the second row

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [21]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [22]:
for i in A:
    print(i)  ## iterating over the rows of the array A and printing the rows for each iteration

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [23]:
for element in np.nditer(A): ## with the help of the nditer() function we can iterate over every element in the array 
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [24]:
for row in A: ## this is a nested loop - first we iterate through the rows of the array A 
    for element in row: ## and when within the loop of A we iterate through each element and print 
        print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [25]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
## We start with creating a Numpy array named 'a' with 30 elements,
## due to the startpoint of indexing being 0, we have integers 0 to 29 which in total is 30 elements, since the stop value is excluded
## Then we declare a variable named 'b' which uses the 'reshape' method in that belong to the ndarray object to rechange the shape of the array
## this method allows us to add/remove dimensions or change number of elements in each dimension.
## We print 'a' which is the original array
## then we print 'b' which is the array with the changes added to it
## in this case we started with a 1D array then reshaped the array into a 3D array. 

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [26]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [27]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [28]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [30]:
def add_mult_matrices(arg1,arg2,operation): ## creating a function called add_mult_matrices, with two arguments for Numpy array and one for operation type
    if not isinstance(arg1, np.ndarray) or not isinstance (arg2, np.ndarray): ## we check if arg1 and arg2 are NumPy array 
        raise ValueError ('the given arguments are not matrices') ## if one of the arg1/arg2 is not a NumPy array then this error is raised 
    
    if operation == 'add': ## we check if the operation is 'add'  
        if arg1.size == arg2.size: ## and if the matrices given have the same element size
            return arg1 + arg2 ## if so then the two arguments are added, 
        else:
            raise ValueError ('The matrices do not have the same sizze..') ## if not then an error is raised 
    elif operation == 'multiply': ## we check if the operation is 'multiply'
        if arg1.size == arg2.size: ## and if the matrices given have the same element size 
            return arg1 * arg2 ## if so then the two arguments are multiplied, 
        else: 
            raise ValueError ('The matrices do not have the same shape..') ## if not then an error is raised


 


In [31]:
A = np.array ([[1, 2, 3]])
B = np.array ([[9, 8, 7]])

In [32]:
print(add_mult_matrices(A, B, 'add'))

[[10 10 10]]


In [33]:
print(add_mult_matrices(A, B, 'multiply'))

[[ 9 16 21]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. 

In [34]:
## 10.1.1
## Definera vektorn x enligt nedan , x = (4,3)
x = np.array([4, 3])

In [35]:
## (a) vilken dimension har vektron x? 
print(x.shape)

(2,)


In [37]:
## (b) beräkna 5x?
print(5 * x)

[20 15]


In [40]:
## (c) beräkna 3x?
print(3 * x)

[12  9]


In [43]:
## (d) beräkna 5x + 3x?
five_x = 5 * x
three_x = 3 * x
print(five_x + three_x)

[32 24]


In [44]:
## (e) beräkna 8x?
print(8 * x)

[32 24]


In [45]:
## (f) beräknar 4x - x? 
four_x = 4 * x
print(four_x - x)

[12  9]


In [48]:
## (g) beräkna x^T, vilken blir den nya dimensionen efter att transponeringen utförts? 
print(x.reshape(-1, 1))

[[4]
 [3]]


In [52]:
## (h) är x + x^T definerat?
print(x + x.reshape(-1, 1))
## we are supposed to get an error but due to broadcasting we get an answer which we shouldn't. 
## so, the answer is no, it's not defined since the dimensions do not match!

[[8 7]
 [7 6]]


In [53]:
## (i) beräkna ||x||.
print(np.linalg.norm(x))

5.0


In [57]:
## 10.1.2 
v = np.array([3, 7, 0, 11])

In [58]:
## (a) vilken dimension har vektorn v?
print(v.shape)

(4,)


In [59]:
## (b) beräkna 2v?
print(2 * v)

[ 6 14  0 22]


In [60]:
## (c) beräkna 5v + 2v?
five_v = 5 * v
two_v = 2 * v
print(five_v + two_v)

[21 49  0 77]


In [61]:
## (d) beräkna 4v - 2v?
four_v = 4 * v
two_v = 2 * v
print(four_v - two_v)

[ 6 14  0 22]


In [62]:
## (e) beräkna v^T, vilken blir den nya dimensionen efter att transponeringen utförts? 
v.reshape(-1, 1)

array([[ 3],
       [ 7],
       [ 0],
       [11]])

In [63]:
## (f) beräkna ||v||.
print(np.linalg.norm(v))

13.379088160259652


In [67]:
## 10.1.3 
## definera vektorn 
# v1 = (4, 3, 1, 5) och v2 = (2, 3, 1, 1)
v1 = ([4, 3, 1, 5])
v2 = ([2, 3, 1, 1])

In [68]:
## (a) beräkna ||v1||.
print(np.linalg.norm(v1))

7.14142842854285


In [70]:
## beräkna ||v1|| - ||v2||.
v1_norm = np.linalg.norm(v1)
v2_norm = np.linalg.norm(v2)
print(v1_norm - v2_norm)

3.2684450823354334


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [72]:
A = np.array([[2, 1, -1,], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2,], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([1,2])
I = np.array([[1, 0], [0, 1]])

In [75]:
## (a) 2A
print(2 * A)

[[ 4  2 -2]
 [ 2 -2  2]]


In [76]:
## (b) B - 2A
two_a = 2 * A
print(B - two_a)

[[ 0 -4  3]
 [ 0 -2 -4]]


In [78]:
## (c) 3C - 2E 
three_c = 3 * C
two_e = 2 * E
print(three_c - two_e)
## its not supposed to be defined but is due to broadcasting

[[ 1  2]
 [ 4 -1]]


In [79]:
## (d) 2D - 3C 
two_d = 2 * D
three_c = 3 * C
print(two_d - three_c)

[[3 2]
 [2 3]]


In [86]:
## (e) D^T + 2D
transp_d = D.T
two_d = 2 * D
print(transp_d + two_d)


[[ 9 12]
 [12  9]]


In [88]:
## (f) 2C^T - 2D^T
transp_2c = 2 * C.T 
transp_2d = 2 * D.T
print(transp_2c - transp_2d)

[[-4 -4]
 [-4 -4]]


In [108]:
## (g) A^T - B 
transp_a = A.T
try:
    result_sub = transp_a - B
except:
    print("not defined!..")

not defined!..


In [121]:
## (h) AC
try: 
   result = A @ B 
except:
    print("not defined!..")

not defined!..


In [114]:
## (i) CD 
print(C @ D)

[[11 10]
 [10 11]]


In [116]:
## (j) CB 
print(C @ B)

[[  8 -10  -3]
 [ 10  -8   0]]


In [117]:
## (k) CI
print(C @ I)

[[1 2]
 [2 1]]


In [119]:
## (l) AB^T 
transp_b = B.T
result = A @ transp_b
print(result)

[[5 2]
 [7 4]]


In [152]:
## 10.2.2 
A = np.array([[2, 3, 4], [5, 4, 1]])

## beräkna AA^T
transp_AA = A.T
print(A @ transp_AA)

[[29 26]
 [26 42]]


In [158]:
## 10.2.3 
A1 = np.array([[1, 2], [2, 4]])
B1 = np.array([[2, 1], [1, 3]])
C1 = np.array([[4, 3], [0, 2]])

In [196]:
## AB
result_ab1 = A1 @ B1
print('AB : ')
print(result_ab1)
print()

## AC 
result_ac1 = A1 @ C1
print('AC : ')
print(result_ac1)
print()

## B
print('B : ')
print(B1)
print()

## C
print('C : ')
print(C1)
print()

print('is AB EQUAL to AC?')
bool_is_equal = np.array_equal(result_ab1, result_ac1)
print(bool_is_equal)
print()

print('is B NOT EQUAL to C?')
bool_is_not_equal = not np.array_equal(B1, C1)
print(bool_is_not_equal)

AB : 
[[ 4  7]
 [ 8 14]]

AC : 
[[ 4  7]
 [ 8 14]]

B : 
[[2 1]
 [1 3]]

C : 
[[4 3]
 [0 2]]

is AB EQUAL to AC?
True

is B NOT EQUAL to C?
True


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [208]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [ ]:
## changes made to the copy do not change the original array. 

In [198]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [199]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [213]:
## Every Numpy array have the attribute 'base' which allows us to simply know what is a view and what is a copy. 
## when using the attribute 'base', if 'None' is returned it means that the array is a copy and that the array owns the data,
## meaning that if any changes happen here, it will not reflect on the original array.
## BUT
## if an actual array is returned it means that it is a view of the orginal array and does not own the data.
## if there would be any changes happening the original array would also be affected.
## thereby v1 in this case is a copy since 'None' is returned and v2 is a view of v1 because a array is returned.
##
## Since v2 is a view of v1 any changes in v2 will be reflected on v1 because they share the same data buffer. 